#!/bin/bash -ex
############################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotz
############################

########## Variables

stamp=$(date +%Y%m%d%H%M%S)
files="bashrc vimrc vim"    # list of files/folders to symlink in homedir

##########

if [ ! -d ~/dotz_old ]; then
    mkdir -p ~/dotz_old
fi

cd ~/dotz

for file in $files; do
    mv ~/.$file ~/dotz_old/.$file.$stamp
    ln -s ~/dotz/.$file ~/.$file
done

# vundle install
if [ -d ~/.vim/bundle/Vundle.vim ]; then
    mv ~/.vim/bundle/Vundle.vim /tmp/Vundle.vim.$stamp
fi
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# install plugins within .vimrc
vim +PluginInstall +qall
